#!/usr/bin/env node
/**
 * Refresh the local ticker data and (optionally) the Algolia search index.
 *
 * Pulls the list of currently active, US-listed symbols from Alpha Vantage's
 * LISTING_STATUS endpoint, regenerates:
 *   - src/app/stocks.ts   (STOCKS:  { symbol, name }[]  — used by the news component)
 *   - src/app/symbols.ts  (SYMBOLS: string[]            — used to filter related news)
 * and, when an Algolia admin key is provided, replaces every record in the
 * `stocks` index that powers the search bar.
 *
 * Usage:
 *   ALGOLIA_ADMIN_KEY=xxxx node scripts/refresh-tickers.mjs
 *
 * Environment variables (loaded from .env automatically via the npm script):
 *   ALPHAVANTAGE_KEY   Alpha Vantage API key (required).
 *   ALGOLIA_APP_ID     Algolia application id (defaults to the public ABHYDU4YXO).
 *   ALGOLIA_INDEX      Algolia index name (defaults to "stocks").
 *   ALGOLIA_ADMIN_KEY  Algolia *admin* key. NEVER commit this. When omitted the
 *                      script only regenerates the local files and skips Algolia.
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

const ALPHAVANTAGE_KEY = process.env.ALPHAVANTAGE_KEY;
const ALGOLIA_APP_ID = process.env.ALGOLIA_APP_ID || 'ABHYDU4YXO';
const ALGOLIA_INDEX = process.env.ALGOLIA_INDEX || 'stocks';
const ALGOLIA_ADMIN_KEY = process.env.ALGOLIA_ADMIN_KEY;

if (!ALPHAVANTAGE_KEY) {
  console.error(
    'ALPHAVANTAGE_KEY is required. Set it in .env or pass it inline, e.g.:\n' +
      '  ALPHAVANTAGE_KEY=xxxx npm run refresh-tickers',
  );
  process.exit(1);
}

// Asset types from LISTING_STATUS we want to surface (matches the original list,
// which included common stocks and ETFs).
const KEEP_ASSET_TYPES = new Set(['Stock', 'ETF']);

/** Minimal RFC-4180-ish CSV parser (handles quoted fields and embedded commas). */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];

    if (inQuotes) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
    } else if (char === ',') {
      row.push(field);
      field = '';
    } else if (char === '\n') {
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else if (char !== '\r') {
      field += char;
    }
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }

  return rows;
}

async function fetchActiveListings() {
  const url =
    `https://www.alphavantage.co/query?function=LISTING_STATUS&apikey=${ALPHAVANTAGE_KEY}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Alpha Vantage request failed: ${res.status} ${res.statusText}`);
  }

  const text = await res.text();
  if (text.trimStart().startsWith('{')) {
    // Alpha Vantage returns a JSON note (not CSV) when rate-limited.
    throw new Error(`Alpha Vantage did not return CSV:\n${text.slice(0, 300)}`);
  }

  const rows = parseCsv(text);
  const header = rows.shift() ?? [];
  const col = (name) => header.indexOf(name);
  const symbolIdx = col('symbol');
  const nameIdx = col('name');
  const assetTypeIdx = col('assetType');
  const statusIdx = col('status');

  const seen = new Set();
  const stocks = [];

  for (const r of rows) {
    const symbol = (r[symbolIdx] || '').trim();
    const name = (r[nameIdx] || '').trim();
    const assetType = (r[assetTypeIdx] || '').trim();
    const status = (r[statusIdx] || '').trim();

    if (!symbol || status !== 'Active' || !KEEP_ASSET_TYPES.has(assetType)) continue;
    if (seen.has(symbol)) continue;

    seen.add(symbol);
    stocks.push({ symbol, name });
  }

  stocks.sort((a, b) => a.symbol.localeCompare(b.symbol));
  return stocks;
}

async function writeDataFiles(stocks) {
  const banner =
    `// AUTO-GENERATED by scripts/refresh-tickers.mjs — do not edit by hand.\n` +
    `// Source: Alpha Vantage LISTING_STATUS (active US-listed stocks + ETFs).\n` +
    `// Last refreshed: ${new Date().toISOString().slice(0, 10)} (${stocks.length} symbols).\n\n`;

  const stocksBody = stocks
    .map((s) => `  { symbol: ${JSON.stringify(s.symbol)}, name: ${JSON.stringify(s.name)} },`)
    .join('\n');
  const stocksFile =
    `${banner}export interface StockListing {\n  symbol: string;\n  name: string;\n}\n\n` +
    `export const STOCKS: StockListing[] = [\n${stocksBody}\n];\n`;

  const symbolsBody = stocks.map((s) => `  ${JSON.stringify(s.symbol)},`).join('\n');
  const symbolsFile = `${banner}export const SYMBOLS: string[] = [\n${symbolsBody}\n];\n`;

  await writeFile(join(repoRoot, 'src/app/stocks.ts'), stocksFile);
  await writeFile(join(repoRoot, 'src/app/symbols.ts'), symbolsFile);
  console.log(`Wrote src/app/stocks.ts and src/app/symbols.ts (${stocks.length} symbols).`);
}

async function algoliaRequest(path, body) {
  const res = await fetch(`https://${ALGOLIA_APP_ID}.algolia.net${path}`, {
    method: 'POST',
    headers: {
      'X-Algolia-API-Key': ALGOLIA_ADMIN_KEY,
      'X-Algolia-Application-Id': ALGOLIA_APP_ID,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`Algolia ${path} failed: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

async function reindexAlgolia(stocks) {
  console.log(`Clearing Algolia index "${ALGOLIA_INDEX}"...`);
  await algoliaRequest(`/1/indexes/${ALGOLIA_INDEX}/clear`, {});

  const CHUNK = 1000;
  for (let i = 0; i < stocks.length; i += CHUNK) {
    const requests = stocks.slice(i, i + CHUNK).map((s) => ({
      action: 'updateObject',
      body: { objectID: s.symbol, symbol: s.symbol, name: s.name },
    }));
    await algoliaRequest(`/1/indexes/${ALGOLIA_INDEX}/batch`, { requests });
    console.log(`  indexed ${Math.min(i + CHUNK, stocks.length)}/${stocks.length}`);
  }
  console.log('Algolia re-index complete.');
}

async function main() {
  console.log('Fetching active listings from Alpha Vantage...');
  const stocks = await fetchActiveListings();
  console.log(`Got ${stocks.length} active symbols.`);

  await writeDataFiles(stocks);

  if (ALGOLIA_ADMIN_KEY) {
    await reindexAlgolia(stocks);
  } else {
    console.log('ALGOLIA_ADMIN_KEY not set — skipped Algolia re-index (files updated only).');
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
